### ISSUE TITLE
"Error writing subchannel to output image, not continuing..."

### ISSUE THREAD

**Issue by SilasLaspada** [claunia/DiscImageChef#161]
### Prerequisites

* [X] Are you running the latest version?
* [X] Can you reproduce the problem in the debug version?

### Check and fill as appropiate:
* [X] I was running DiscImageChef under Windows 10...
* [ ] I was running DiscImageChef under Linux [version here]...
* [ ] I was running DiscImageChef under FreeBSD [version here]...
* [ ] I was running DiscImageChef under macOS [version here]...
* [ ] ...using .NET Framework [version here]...
* [ ] ...using .NET Core [version here]...
* [ ] ...using Mono [version here]...
* [ ] ...in 32-bit
* [ ] ...in 64-bit

### Description

When reading a CD-ROM, DiscImageChef tells me "Error writing subchannel to output image, not continuing..." and stops.

### Exact command line used:

DiscImageChef.exe dump-media -i E: -o test.mds

### Expected behavior:
It should dump the CD-ROM without using -f to force it (which seems to work).

### Actual behavior:
"Error writing subchannel to output image, not continuing..."

### If command was expected to work with a device fill this:

* **Manufacturer**: Memorex
* **Model**: MRX-650LE v7
* **Bus**:
    * [ ] Parallel ATA
    * [ ] Serial ATA
    * [ ] SCSI (any)
    * [ ] ATAPI (mark above if parallel or serial)
    * [X] USB
    * [ ] FireWire
    * [ ] PCMCIA
    * [ ] SecureDigital
    * [ ] MultiMediaCard
    
### Output of command execution with debug output enabled
```
The Disc Image Chef 4.0.99.0
Copyright c 2011-2018 Natalia Portillo

DEBUG (Dump-Media command): --debug=True
DEBUG (Dump-Media command): --verbose=False
DEBUG (Dump-Media command): --device=E:
DEBUG (Dump-Media command): --raw=False
DEBUG (Dump-Media command): --stop-on-error=False
DEBUG (Dump-Media command): --force=False
DEBUG (Dump-Media command): --retry-passes=5
DEBUG (Dump-Media command): --persistent=False
DEBUG (Dump-Media command): --resume=True
DEBUG (Dump-Media command): --lead-in=False
DEBUG (Dump-Media command): --encoding=
DEBUG (Dump-Media command): --output=test.mds
DEBUG (Dump-Media command): --format=
DEBUG (Dump-Media command): --force=False
DEBUG (Dump-Media command): --options=
DEBUG (Dump-Media command): Parsed options:
DEBUG (SCSI Device): INQUIRY took 1.0035 ms.
DEBUG (Windows devices): NT device path:
InstanceId: USB\VID_0718&PID_4006\SSFCO0023411220
DEBUG (ATA Device): IDENTIFY PACKET DEVICE took 0.5431 ms.
Output image format: Alcohol 120% Media Descriptor Structure.
DEBUG (SCSI Device): TEST UNIT READY took 4.0135 ms.
DEBUG (SCSI Device): GET CONFIGURATION took 3.0105 ms.
DEBUG (SCSI Device): READ TOC/PMA/ATIP took 3.0099 ms.
DEBUG (SCSI Device): READ TOC/PMA/ATIP took 2.0064 ms.
DEBUG (SCSI Device): READ DISC INFORMATION took 3.512 ms.
DEBUG (SCSI Device): READ TOC/PMA/ATIP took 4.0137 ms.
DEBUG (SCSI Device): READ TOC/PMA/ATIP took 2.0068 ms.
DEBUG (SCSI Device): READ TOC/PMA/ATIP took 5875.5214 ms.
Checking if drive supports full raw subchannel reading...
DEBUG (SCSI Device): READ CD took 107.8675 ms.
Full raw subchannel reading supported...
Building track map...
Checking mode for track 1...
DEBUG (SCSI Device): READ CD took 6.0206 ms.
Track 1 is MODE1
DEBUG (SCSI Device): READ CD took 0 ms.
DEBUG (SCSI Device): READ CD took 0 ms.
DEBUG (SCSI Device): READ CD took 18.0619 ms.
Reading 16 sectors at a time.
Device reports 331047 blocks (810403056 bytes).
Device can read 16 blocks at a time.
Device reports 2448 bytes per logical block.
SCSI device type: MultiMediaDevice.
Media identified as CDROM.
DEBUG (SCSI Device): READ CD took 0 ms.
Error writing subchannel to output image, not continuing...
Uploading partial statistics file C:\Users\silas\AppData\Roaming\Claunia.com\DiscImageChef\Statistics\PartialStats_20180125223607822.xml
```

**Comment by claunia** [comment]
@SilasLaspada please try again 😛

**Comment by SilasLaspada** [comment]
I tried on the newest commit and it works now! Thanks for fixing it so quickly! :)

**Comment by claunia** [comment]
Please note that part of the code is still work is progress and I have not checked that the images are readable by other software or even contains correct data. Particularly I don’t even have Alcohol installed to test if it reads the images I create.

**Comment by SilasLaspada** [comment]
Both alcohol and wincdemu mount it properly and I can convert it to iso just fine, so it looks pretty promising!
