### ISSUE TITLE
Problems dumping MO discs

### ISSUE THREAD

**Issue by Altheos** [claunia/DiscImageChef#167]
### Prerequisites

* [x] Are you running the latest version? 4.0.1.0
* [ ] Can you reproduce the problem in the debug version? can't compile it

### Check and fill as appropiate:
* [x ] I was running DiscImageChef under Linux Ubuntu 17.10
* [x] ...using Mono  4.6.2.7
* [x] ...in 32-bit

### Description

When dumping MO Disc, if DIC encounter a "bad" sector or a read problem, it can't pass thru.
The MO drive seems to be stuck trying to read. After reboot, DIC can read sectors and retry "bad" sectors successfully. Could possibly be a SCSI module problem.

### Exact command line used:
sudo mono DiscImageChef.exe dump-media -i /dev/sdb -v -d --persistent=true -f -p 5 -w doe

### Expected behavior:
DIC should bypass bad sector and not hang SCSI drive

### Actual behavior:
SCSI drive can't read more sectors and a reboot is needed to recover

### If command was expected to work with a device fill this:

* **Manufacturer**: IBM
* **Model**: MTA-3230
* **Bus**:
    * [x] SCSI (any)

    
### Output of command execution with debug output enabled
DEBUG (SCSI Reader): READ error:
SCSI SENSE: MEDIUM ERROR
On logical block 125557
ID CRC OR ECC ERROR

Reading sector 125568 of 446325 (0,032 MiB/sec.)DEBUG (SCSI Device): READ (12) took 15620 ms.
DEBUG (SCSI Reader): READ error:

Reading sector 125632 of 446325 (0,002 MiB/sec.)DEBUG (SCSI Device): READ (12) took 47104 ms.
DEBUG (SCSI Reader): READ error:

STATE CUE CARD: (? means a positive number, usually 1 or 2, * means any number)
	0x0	- starting (GOOD, unless the thread is running managed code)
	0x1	- running (BAD, unless it's the gc thread)
	0x2	- detached (GOOD, unless the thread is running managed code)
	0x?03	- async suspended (GOOD)
	0x?04	- self suspended (GOOD)
	0x?05	- async suspend requested (BAD)
	0x?06	- self suspend requested (BAD)
	0x*07	- blocking (GOOD)
	0x?08	- blocking with pending suspend (GOOD)
--thread 0xb58005e0 id 0xb7967b40 [(nil)] state 105  
--thread 0x8b8d1e0 id 0xb7c8c700 [(nil)] state 1  GC INITIATOR
WAITING for 1 threads, got 0 suspended
suspend_thread suspend took 200 ms, which is more than the allowed 200 ms

[ 1224.856804] scsi host2: scsi scan: INQUIRY result too short (8), using 36
[ 1226.977866] sd 2:0:0:0: Attached scsi generic sg2 type 7
[ 1226.996147] sd 2:0:0:0: [sdb] 446325 512-byte logical blocks: (229 MB/218 MiB)
[ 1227.000442] sd 2:0:0:0: [sdb] Write Protect is on
[ 1227.000459] sd 2:0:0:0: [sdb] Mode Sense: 49 03 80 08
[ 1227.009274] sd 2:0:0:0: [sdb] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
[ 1227.177706]  sdb:
[ 1227.214147] sd 2:0:0:0: [sdb] Attached SCSI removable disk
[ 1230.093834] sd 2:0:0:0: [sdb] tag#0 FAILED Result: hostbyte=DID_ABORT driverbyte=DRIVER_OK
[ 1230.093857] sd 2:0:0:0: [sdb] tag#0 CDB: ATA command pass through(16) 85 06 20 00 05 00 fe 00 00 00 00 00 00 40 ef 00
[ 1420.268231] sdb: detected capacity change from 228518400 to 0

**Comment by claunia** [comment]
Please attach dmesg lines from the moment the first error happened, I need to observe exact device behavior when retries.

New version includes an improved skipping algorithm when bad sectors are found that may alleviate that problem.

Nonetheless some devices after a few bad sector reads get stuck and there is no way to prevent or solve that except rebooting. I have pending to add a device reset if this is detected to happen but there's no guarantee it will work at all.

If resume works, it's a nuisance having to reboot but at least you keep getting data, if it doesn't work please create another issue, as it's a different problem.
