### ISSUE TITLE
Various errors with CD-ROM XA that has multiple tracks

### ISSUE THREAD

**Issue by SilasLaspada** [claunia/DiscImageChef#176]
Trying to convert an MDF/MDS file pair that is CD-ROM XA that has 2 tracks results in the program crashing with the command window having been spammed with "Converting sectors x to x in track 2 (xx.xx% done)Error Can't found track containing x writing sector x, continuing..." before the crash. A very similar crash occurs when dumping the disc to MDF/MDS. The image is dumped correctly when using the BIN/CUE format. I have had the same issue with similar CD-ROM XA discs, but seemingly only if they had multiple tracks. I attached all the logs and I'll try to get a link to the image file up ASAP, let me know if you need anything else! [Logs.zip](https://github.com/claunia/DiscImageChef/files/1998618/Logs.zip)

**Comment by SilasLaspada** [comment]
Here is a link to the image file on Dropbox: https://www.dropbox.com/s/rxwgpuwgtx6shrv/Image%20file%20%28from%20Alcohol%20120%25%29.zip

**Comment by claunia** [comment]
I'll take a look as soon as I can

**Comment by claunia** [comment]
@SilasLaspada the bug only affected reading images, the image seems to have been created correctly.
