### ISSUE TITLE
Big inner lead-outs in multisession discs should not give error

### ISSUE THREAD

**Issue by claunia** [claunia/DiscImageChef#181]
In some multisession discs the lead-out for the inner sessions is several hundreds of sectors big. These sectors are shown by errors in some drive. They should be recognized and read if possible but not considered as errors.

See #179 for example image.

**Comment by claunia** [comment]
@SilasLaspada this will have to wait, just ignore those errors, I cannot check that without a disc that fails.

**Comment by SilasLaspada** [comment]
Ok, I understand. If you want, I could send you this disc if you can't find another one to work with. I would want it back eventually, but you could take as much time as you need to get it to work.

**Comment by claunia** [comment]
@SilasLaspada I'll try to find a CD+ in the next weeks, that should be enough

**Comment by SilasLaspada** [comment]
Ok, sounds good.

**Comment by claunia** [comment]
https://www.ebay.co.uk/itm/142835264962 is this? wow that's pretty expensive shipping costs for a CD...

**Comment by SilasLaspada** [comment]
That is pretty bad for shipping, but that appears to be the disc.

**Comment by SilasLaspada** [comment]
So is there no way to dump a CD in such a way that you wouldn't need to buy an actual copy at all? Like would MDF/MDS allow you to burn it to a disc and make your tests using that disc?

**Comment by claunia** [comment]
No, for the lead-out issue I need specifically a disc that presents the problem. I have dumped a few CD+ and never encountered this problem :disappointed:

**Comment by SilasLaspada** [comment]
Darn, ok. Could the disc itself just be bad, or is it a weird edge case that DiscImageChef can't handle yet?

**Comment by claunia** [comment]
@SilasLaspada it's a weird edge case. Lead-out uses "negative sectors", so if session 1 ends in sector 1000, lead-out is 0xAAxxxxxx, then session 2 starts at sector 1001, then lead-out again is 0xAAxxxxxx. At least that's what Yellow Book specifies.

**Comment by SilasLaspada** [comment]
Ok, thank you for explaining that. The offer still stands to send the disc to you, but you may have to pay or split the shipping cost if it's going to be $20+.

**Comment by claunia** [comment]
I was thinking. 

There are two kind of errors in a CD.

The CIRC error. In this case most drives don’t return any data at all (and in the case of lead-out it always fails with this kind of error and only a handful of drives can read it).

And the ECC error. This only happens on data tracks and most drives can return data.

Alcohol is known to write fake sectors that fail with ecc errors when it finds circ errors.

So the problem arises that there the leadout it supposedly in audio format, and dic finds circ errors, but alcohol is writing data sectors with ecc errors.

So we need to try to see what’s really there.

Unfortunately there are only two ways and none of them guaranteed to work.

* Dump the disc with an audio extractor (eac or cdparanoia) using an audio trap disc.
* Dump the disc in scrambled mode with a plextor cdrw (using discimagecreator and the raw file because its cue/bin introduces the same fake sectors as alcohol)

If you could generate both kind of images, or at leaat one of them, I can work without the disc.

**Comment by SilasLaspada** [comment]
If I understand correctly, the second option would need a plextor drive, right? I'm looking to get one of those eventually, but not in the near future. The first one sounds more promising (especially if I don't need any extra hardware), but what is an audio trap disc?

**Comment by claunia** [comment]
An audio trap disc is a disc with a fake toc saying it has a single track of 120min of audio, that you put inside the drive and you change it for the real one without using the eject button. It can be recorded on a Cd-R and there are videos on how to use it

**Comment by SilasLaspada** [comment]
Ok, is this a disc image that I could use for it? https://archive.org/details/audio-trap-disc Also, could you please link one of those videos, Google isn't being very helpful with this.

**Comment by SilasLaspada** [comment]
Ok, I think I've got the basic principle down now. I will need to know exactly what you want me to do with EAC though, because it seems to be freezing up with the audio trap disc alone and when I put the problem disc in after. I am following this guide http://wiki.redump.org/index.php?title=Sega_Dreamcast, in particular the startstop.exe seems very useful as it stops the drive motor. The only issue is that the drive light turns green and everything seems to start up again when I close the tray, so I don't know if that messes things up or not. Also, I burned the same audio trap disc that I mentioned before using CloneCD and burning it as a music disc.

**Comment by claunia** [comment]
If you are gently pushing the drive it should not start blinking the led, if it does well you'll have to try another drive. I never tried it with a slim drive but I think they don't support trap discs because contrary to full height drives, that detect a disc change because you click to open them, slim ones do detecting they're being closed.

About EAC freezing I don't know, try cdparanoia for windows and if not redump's DiscImageCreator.

I have not tried DiscImageChef with a trap disc so I don't know. If it sees a single 120m track, great use it with --persistent (but use dicformat or bin/cue output).

The --persistent is optional but is designed to keep data returned from the drive (if the drive supports it, plextor does, some LG do some don't) in the case of CIRC error. And won't do any damage if the drive doesnt support it (and should detect that's the case and tell you).

Also, note, if you're dumping a disc whose first track (or first track of any session) is audio, you should do with a drive that supports "--lead-in" option because there may be audio data before LBA 0.

**Comment by SilasLaspada** [comment]
Ok, I'll have to get a better setup together then, as my main reader is a slim drive. I should have more than enough drives lying around to get something working. Another question, is the audio trap disc supposed to be a CD or a DVD? It seems that it should be a CD, but iirc an Audio CD can only hold 80 minutes. Or is that the point of the trap disc, to pretend to be longer than a normal CD can be?

**Comment by claunia** [comment]
That is the point, it pretends to be as long as a Dreamcast disc.

**Comment by SilasLaspada** [comment]
Ok, just making sure.

**Comment by SilasLaspada** [comment]
Ok, I got it working and DiscImageCreator was able to read about 300MB worth of data, which I believe is all of the audio tracks. Let me know if you need me to do it with a data trap disc as well. https://www.dropbox.com/s/a3f96k8e9tbffos/DiscImageCreator.zip?dl=0

**Comment by claunia** [comment]
No need, got a disc which exhibits same problem, I'll work with it.

**Comment by SilasLaspada** [comment]
Ok, good!

**Comment by SilasLaspada** [comment]
Here you go: https://www.dropbox.com/s/ixxz1uvfwhift7x/OEP%20CUE.zip?dl=0

**Comment by claunia** [comment]
Need also the output from the command not only the log file, specifically the lines:
`Track x starts at LBA y and ends at LBA z`

**Comment by claunia** [comment]
@SilasLaspada try now

**Comment by SilasLaspada** [comment]
It works perfectly now, thank you!
