### ISSUE TITLE
Add support for VMWare images

### ISSUE THREAD

**Issue by claunia** [claunia/DiscImageChef#39]

**Comment by darkstar** [comment]
The VMDK file format is pretty well documented: https://www.vmware.com/support/developer/vddk/vmdk_50_technote.pdf

Interesting tidit: There are oer 10 different VMDK subformats (some of which are identical, but some are quite special...)

**Comment by claunia** [comment]
I know, that's why I'm doing other disk image formats first ;)

**Comment by claunia** [comment]
Now I need to get compressed, encrypted, vmfs and streamoptimized images for testing.

**Comment by darkstar** [comment]
I can get you some ESX images (thin, eager thick, lazy thick and RDM) if that's  what you mean by "VMFS". StreamOptimized are probably inside OVF templates (I will take a look). I have not yet encountered compressed images but encrypted images can be created by VMware workstation.

I'll see what I can find

**Comment by claunia** [comment]
Ok I'll try them asap.

I've read on the documentation that the disk descriptor can indicate if the vmdk is encrypted.
We'll see.

But encryption will nonetheless not be implemented until compression is, at least Iwant to detect and fail gracefully.
