### ISSUE TITLE
Filesystem not identified on multisession image created by Aaru

### ISSUE THREAD

**Issue by TheRogueArchivist** [claunia/DiscImageChef#661]
### Prerequisites

* [X] Are you running the latest version? (Newest on v5.3 branch)
* [X] Can you reproduce the problem in the debug version?

### Check and fill as appropriate:
* [X] I was running Aaru under Windows 10...
* [ ] I was running Aaru under Linux [version here]...
* [ ] I was running Aaru under macOS [version here]...
* [ ] ...in 32-bit
* [X] ...in 64-bit
* [X] ...using an Intel / AMD processor
* [ ] ...using an ARM or Apple Silicon processor
* **Device manufacturer**: Plextor
* **Model**: 760A
* **Bus**:
    * [ ] Parallel ATA
    * [ ] Serial ATA
    * [ ] SCSI (any)
    * [ ] ATAPI (mark above if parallel or serial)
    * [ ] USB
      * **USB cable manufacturer**:
      * **USB cable model**:
    * [ ] FireWire
    * [ ] PCMCIA
    * [ ] SecureDigital
      * [ ] Using a USB card reader
          * **USB card reader manufacturer**:
          * **USB card reader model**:
    * [ ] MultiMediaCard
        * [ ] Using a USB card reader
            * **USB card reader manufacturer**:
            * **USB card reader model**:
* [X] I was dumping media (disk, tape, etc)...
* [ ] I was analyzing media (disk, tape, etc)...
* [ ] I was scanning media (disk, tape, etc)...

### Description

No filesystem commands are able to recognize the FS on the CD, but an image of the same CD created with DIC is read by Aaru without any issue. This can be easily demonstrated with the filesystem info command. There were 0 errors dumping and 0 errors in verification. Both the original Aaruf image and a CUE image converted from the Aaruf image are affected.

### Exact command line used:

`aaru fs info OEP.aaruf`

### Expected behavior:

Aaru to recognize the filesystem.

### Actual behavior:

No filesystem identified.

### Output of command execution with debug output enabled
```
https://pastebin.com/R6vhXWYh
```

### Media details

Old El Paso Recipes for Family Fun

**Comment by claunia** [comment]
Fixed in 40ed1b19e2e1b0de7997891bd652cb09d6d469d7
