### ISSUE TITLE
New device report: PLDS DVD+-RW DU-8A5HH

### ISSUE THREAD

**Issue by darkstar** [claunia/DiscImageChef#665]
Aaru told me to create a device report and attach it to a GitHub issue. So here goes ;-)
[PLDS_DVD+-RW DU-8A5HH_SD12.json.gz](https://github.com/aaru-dps/Aaru/files/7205053/PLDS_DVD%2B-RW.DU-8A5HH_SD12.json.gz)

**Comment by claunia** [comment]
Partial report added to database.
Audio CD must not contain data tracks.
DVD+ disc reports are invalid for some reason.
