### ISSUE TITLE
Drive Report for TSSTcorp_DVD+-RW TS-H653A_D300

### ISSUE THREAD

**Issue by InternalLoss** [claunia/DiscImageChef#673]
[TSSTcorp_DVD+-RW TS-H653A_D300.zip](https://github.com/aaru-dps/Aaru/files/7247405/TSSTcorp_DVD%2B-RW.TS-H653A_D300.zip)

**Comment by claunia** [comment]
Report partially added, try with another CD-ROM, please do not send reports using USB adapters.
