### ISSUE TITLE
Drive Report - HL-DT-ST DVDRW  GX40N (Apple SuperDrive)

### ISSUE THREAD

**Issue by InternalLoss** [claunia/DiscImageChef#674]
[HL-DT-ST_DVDRW  GX40N_RQ00.zip](https://github.com/aaru-dps/Aaru/files/7247431/HL-DT-ST_DVDRW.GX40N_RQ00.zip)
NOTE: Wii discs automatically eject themselves from the drive before they can even get ready.

NOTE2: I didn't test GCN or DVD+RW as both are 8cm discs and this is a 12cm only slot-loading drive.

**Comment by claunia** [comment]
Report added to database, please update.
