### ISSUE TITLE
"Exception has been thrown by the target of an invocation." dumping CD-ROM

### ISSUE THREAD

**Issue by TheRogueArchivist** [claunia/DiscImageChef#683]
### Prerequisites

* [X] Are you running the latest version?
* [X] Can you reproduce the problem in the debug version?

### Check and fill as appropriate:
* [X] I was running Aaru under Windows 10...
* [ ] I was running Aaru under Linux [version here]...
* [ ] I was running Aaru under macOS [version here]...
* [ ] ...in 32-bit
* [X] ...in 64-bit
* [X] ...using an Intel / AMD processor
* [ ] ...using an ARM or Apple Silicon processor
* **Device manufacturer**: ASUS
* **Model**: BW16D1HT
* **Bus**:
    * [ ] Parallel ATA
    * [X] Serial ATA
    * [ ] SCSI (any)
    * [ ] ATAPI (mark above if parallel or serial)
    * [ ] USB
      * **USB cable manufacturer**:
      * **USB cable model**:
    * [ ] FireWire
    * [ ] PCMCIA
    * [ ] SecureDigital
      * [ ] Using a USB card reader
          * **USB card reader manufacturer**:
          * **USB card reader model**:
    * [ ] MultiMediaCard
        * [ ] Using a USB card reader
            * **USB card reader manufacturer**:
            * **USB card reader model**:
* [X] I was dumping media (disk, tape, etc)...
* [ ] I was analyzing media (disk, tape, etc)...
* [ ] I was scanning media (disk, tape, etc)...

### Description

Aaru 6.0 (5.3 unaffected) crashes partway through dumping a disc with "Exception has been thrown by the target of an invocation.". Seems to crash dumping to multiple formats, tested include Aaruf and CUE.

### Exact command line used:

`Aaru m dump D: test.aaruf]`

### Output of command execution with debug output enabled
https://pastebin.com/2Xg3qJBH

### Media details

Swift Classics Card Games for Windows (CD-ROM XA)

**Comment by claunia** [comment]
It is fixed in ee09f7c57e9d23e615d7f8090b25fc4b0d1e83b1
