### ISSUE TITLE
[ISO9960] Somes files not being correctly listed/extracted

### ISSUE THREAD

**Issue by robin-francois** [claunia/DiscImageChef#708]
### Version

5.3.0

### Tested debug version?

- [X] Yes

### Which operating systems have you used?

- [ ] Windows
- [X] Linux
- [ ] macOS
- [ ] Other

### What is the architectural bit size you're using?

- [ ] 32-bit
- [X] 64-bit
- [ ] Unsure or unknown

### What processor are you using?

- [X] An Intel or AMD
- [ ] An ARM or Apple Silicon
- [ ] Unsure or unknown

### Image format

Aaru File Format

### Application that created the image

Aaru

### What were you doing when it failed?

- [ ] I was converting the image to another format...
- [ ] I was retrieving image information...
- [ ] I was retrieving filesystem information...
- [X] I was listing the filesystem contents...
- [X] I was extracting the filesystem contents...
- [ ] I was creating a metadata sidecar...
- [ ] I was checksumming the image...
- [ ] I was verifying the image...
- [ ] I was calculating the image entropy...

### Filesystem

ISO9660

### Description

When both listing and extracting files from an Aaru image from a DVD+R DL formatted in ISO9960 with 3956112 sectors, some files are missing.

By converting the image to ISO, or by reading the media using other tools, 10 more files can be found on the image.

### Exact command line used

aaru fs extract image.aaru content2 -d

### Expected behavior

All files are being listed correctly.

### Actual behavior

When both listing and extracting files from an Aaru image generated with Aaru from a DVD+R DL formatted in ISO9960 with 3956112 sectors, the files after sector 3954263 are missing.

By converting the image to ISO, or by reading the media using other tools, 10 files can be found on the image after sector 3954263 (see output below).

### Output of command execution with debug output enabled

```shell
Excerpt of the full output:

[...]
DEBUG (ISO9660 Plugin): Sector 3954256, Cooked, Mode 0/1 / Mode 2 Form 1
DEBUG (ISO9660 Plugin): Sector 3954257, Cooked, Mode 0/1 / Mode 2 Form 1
DEBUG (ISO9660 Plugin): Sector 3954258, Cooked, Mode 0/1 / Mode 2 Form 1
DEBUG (ISO9660 Plugin): Sector 3954259, Cooked, Mode 0/1 / Mode 2 Form 1
DEBUG (ISO9660 Plugin): Sector 3954260, Cooked, Mode 0/1 / Mode 2 Form 1
DEBUG (ISO9660 Plugin): Sector 3954261, Cooked, Mode 0/1 / Mode 2 Form 1
DEBUG (ISO9660 Plugin): Sector 3954262, Cooked, Mode 0/1 / Mode 2 Form 1
DEBUG (ISO9660 Plugin): Sector 3954263, Cooked, Mode 0/1 / Mode 2 Form 1
Written 278474 bytes of file 9997056.pdf to content2/ISO9660/Disc/Data/9997056.pdf
DEBUG (Aaru Format plugin): Memory snapshot: 325426736 bytes
DEBUG (Aaru Format plugin): Memory snapshot: 333815400 bytes
DEBUG (Aaru Format plugin): Memory snapshot: 333815400 bytes
DEBUG (ISO9660 Plugin): Sector 835, Cooked, Mode 0/1 / Mode 2 Form 1
Written 37 bytes of file AUTORUN.INF to content2/ISO9660/Disc/AUTORUN.INF
DEBUG (ISO9660 Plugin): Sector 836, Cooked, Mode 0/1 / Mode 2 Form 1
DEBUG (ISO9660 Plugin): Sector 837, Cooked, Mode 0/1 / Mode 2 Form 1
DEBUG (ISO9660 Plugin): Sector 838, Cooked, Mode 0/1 / Mode 2 Form 1
DEBUG (ISO9660 Plugin): Sector 839, Cooked, Mode 0/1 / Mode 2 Form 1

```

Output of `isoinfo -l -i converted_image.iso` on the converted ISO image:
```
[...]
----------   0    0    0          308060 Aug 16 2012 [3954264 00]  9997092.PDF
----------   0    0    0          332005 Aug 16 2012 [3954415 00]  9997338.PDF
----------   0    0    0          151021 Aug 16 2012 [3954578 00]  9997344.PDF
----------   0    0    0          196866 Aug 16 2012 [3954652 00]  9997346.PDF
----------   0    0    0          251528 Aug 16 2012 [3954749 00]  9997350.PDF
----------   0    0    0          217776 Aug 16 2012 [3954872 00]  9997372.PDF
----------   0    0    0          420998 Aug 16 2012 [3954979 00]  9997448.PDF
----------   0    0    0          523775 Aug 16 2012 [3955185 00]  9997662.PDF
----------   0    0    0          993513 Aug 16 2012 [3955441 00]  9997952.PDF
----------   0    0    0          373166 Aug 17 2012 [3955927 00]  9998740.PDF
```

### Affected image

Image available on demand (@r2gf_ on Aaru's Discord)

**Comment by robin-francois** [comment]
Image shared privately with @claunia and @SilasLaspada.

**Comment by TheRogueArchivist** [comment]
Can confirm, Aaru fails to extract 10 files from the image that are able to be seen and extracted from the ISO image using 7-zip.
