### ISSUE TITLE
[ISO9660] Non-printable characters in Joliet namespace when listing or extracting

### ISSUE THREAD

**Issue by robin-francois** [claunia/DiscImageChef#718]
### Version

5.3.0

### Tested debug version?

- [X] Yes

### Which operating systems have you used?

- [ ] Windows
- [X] Linux
- [ ] macOS
- [ ] Other

### What is the architectural bit size you're using?

- [ ] 32-bit
- [X] 64-bit
- [ ] Unsure or unknown

### What processor are you using?

- [X] An Intel or AMD
- [ ] An ARM or Apple Silicon
- [ ] Unsure or unknown

### Image format

AaruFormat

### Application that created the image

Aaru

### What were you doing when it failed?

- [ ] I was converting the image to another format...
- [ ] I was retrieving image information...
- [X] I was retrieving filesystem information...
- [X] I was listing the filesystem contents...
- [X] I was extracting the filesystem contents...
- [ ] I was creating a metadata sidecar...
- [ ] I was checksumming the image...
- [ ] I was verifying the image...
- [ ] I was calculating the image entropy...

### Filesystem

ISO9660

### Description

When performing file listing or file extraction of the image in the Joliet namespace, the filenames and folders names of the two partitions in ISO9660 are 'non-printable', which indicates an issue with caracter encoding.

### Exact command line used

aaru fs ls

### Expected behavior

File listing with 'printable' characters in the Joliet namespace.

### Actual behavior

File listing with 'non-printable' characters. With namespace *romeo*, output is printable, but the filenames are shortened.

Example of shortened filenames with `-n romeo`:
```
Identified by ISO9660 Filesystem.
Root directory
                         <DIR>                 FONTS_
                         <DIR>                 IMAGES
                             82       174,080  DESKTOP_.DB
                com.apple.FinderInfo    16
                            178     1,029,554  DESKTOP_.DF
                com.apple.FinderInfo    16
                              0             0  ICON_
                com.apple.ResourceFork  486
                           1030       297,266  PR-STORY.PDF
                com.apple.FinderInfo    16
                            688       696,064  PR_-STOR.Y
                com.apple.ResourceFork  342
```

### Output of command execution with debug output enabled

```shell
See full output.txt in the "Affected image" block below.
```

### Affected image

Image download link shared with @claunia and @SilasLaspada
[output.txt](https://github.com/aaru-dps/Aaru/files/8204646/output.txt)

**Comment by claunia** [comment]
Checked the image and the Joliet table violates the Joliet specification. The encoding is not UCS-2 (it is indeed, none of a dozen I tried).

The Apple Extensions do not include a filename therefore the only available name is the shortened one until HFS support is implemented, sorry.
