### ISSUE TITLE
[Feature request] Parse additional DIC data when converting ISO images

### ISSUE THREAD

**Issue by TheRogueArchivist** [claunia/DiscImageChef#737]
### Type

Other...

### Description

When dumping DVDs and BDs, DIC outputs several additional files that contain data about the disc that are included directly into other image formats, such as MDS or Aaruf. It would be useful if Aaru were able to parse these files when converting these images, so the additional information is preserved directly into the output image.

Examples of these include *ImageName*_DMI.bin, *ImageName*_PFI.bin, *ImageName*_PIC.bin, and *ImageName*_SS.bin.

### Context

This would make it much easier to make use of the additional data that DIC dumps, but doesn't include in a directly usable format. It would also improve the overall quality of Aaruf images created from conversion of DIC dumps.

**Comment by claunia** [comment]
We store those sidecars since years ago, they should be the ones fixing to use our naming scheme not us. Won't fix.
