### ISSUE TITLE
[Feature request] Use AccurateRip database for drive offset detection

### ISSUE THREAD

**Issue by saturnized** [claunia/DiscImageChef#740]
### **Type**

Possible QOL improvement
### **Description**

AccurateRip uses a database of drives that could aide in automatic detection of drive offset.
### **Context**

Aaru currently seems to have issues detecting drive offset.
### **Documentation**

http://www.accuraterip.com/driveoffsets.htm

**Comment by claunia** [comment]
We already use AccurateRip's database with our own additions. Closing as already fixed.
