### ISSUE TITLE
"Unknown error code 1" for Blu-ray type drive (LG WH14NS40)

### ISSUE THREAD

**Issue by ghost** [claunia/DiscImageChef#797]
### Version

5.3.0

### Tested debug version?

- [X] Yes

### Which operating systems have you used?

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Other

### What is the architectural bit size you're using?

- [ ] 32-bit
- [X] 64-bit
- [ ] Unsure or unknown

### What processor are you using?

- [X] An Intel or AMD
- [ ] An ARM or Apple Silicon
- [ ] Unsure or unknown

### Description

aaru doesn't seem to recognize my BD drive. Commands return `unknown error code 1`.

Device info:

Type: Internal Blu-ray
Mfg: LG
Model: WH14NS40
Device Manager Name: HL-DT-ST BD-RE WH14NS40
Firmware version: 1.05, ~January 2022
Interface: SATA

Tried with aaru v5.3.2 and v6.0.0alpha9
aaru v5.3.2 has worked with two other DVD drives on my system without any issues

### Exact command line used

`aaru device info m: -d`

### Expected behavior

Expected to at least be able to get the info from the device.

### Actual behavior

`device info` and `media dump` both raise `unknown error code 1`. Commands appear to fail at the "ATA DEVICE: IDENTIFY DEVICE" step.

### Output of command execution with debug output enabled

```shell
PS C:\> aaru device info m: -d
aaru 5.3.2+f4fef21d
Copyright c 2011-2023 Natalia Portillo

DEBUG (Device-Info command): --debug=True
DEBUG (Device-Info command): --device=m:
DEBUG (Device-Info command): --output-prefix=
DEBUG (Device-Info command): --verbose=False
DEBUG (ATA Device): IDENTIFY PACKET DEVICE took 3.3977 ms.
DEBUG (ATA Device): IDENTIFY DEVICE took 0.0191 ms.
Unknown error code 1
DEBUG (Submit stats): Uploading statistics
```
```

**Comment by claunia** [comment]
Can you please try with Aaru 5.3.1?

**Comment by ghost** [comment]
Same issue and output:

```
PS C:\Applications\aaru-5.3.1_windows_x64-dbg> ./aaru device info -d m:
aaru 5.3.1
Copyright c 2011-2022 Natalia Portillo

DEBUG (Device-Info command): --debug=True
DEBUG (Device-Info command): --device=m:
DEBUG (Device-Info command): --output-prefix=
DEBUG (Device-Info command): --verbose=False
DEBUG (ATA Device): IDENTIFY PACKET DEVICE took 3.5602 ms.
DEBUG (ATA Device): IDENTIFY DEVICE took 0.0197 ms.
Unknown error code 1
Uploading statistics
```

**Comment by claunia** [comment]
Are you using the official firmware or a modified one?

**Comment by ghost** [comment]
It's LG's official firmware. Just flashed it this morning.

**Comment by claunia** [comment]
Is it latest version?
If not can you upgrade to latest version?
Are you using your motherboard's SATA ports?
If so can you specify your motherboard model and the port it is connected to.
Can you try under Linux?

**Comment by ghost** [comment]
- Latest firmware version: yes
- Using Motherboard's SATA port; HOWEVER, they're the third-party Marvell GSATA. I've never used them until now, but I'm out of the lower "standard" ports and forgot the others were Marvell.
- Motherboard: Gigabyte 990FXA-UD5 R5
- Connected to Port 0 on the Marvell side (port "6" on the motherboard pcb numbering)
- I don't have a Linux installation handy on this machine. Happy to try it, but it would take some time.

I can try swapping a HDD into the Marvell port and give the BD drive a try on the first-party SATA ports+drivers. The existing DVD drive that's been working fine with aaru is on a first-party port, so that could very well be the difference.

**Comment by claunia** [comment]
That is most probably the reason, those ports (as well as slot cards, like PCI and PCIe cards) usually install third party drivers that don't declare themselves as conforming to the ATA Pass-Throught Interface from Windows.

Due to the many many of those drivers we cannot support them under Windows atm.

To confirm, if you do `aaru device list` you'll see if it says "Not supported" or "RAID", it won't work.

Those ports do however work under Linux because there is no such concept of third party drivers.

Please confirm if the drive works in one of the chipset ports.

**Comment by ghost** [comment]
Swapping to a chipset port fixed the issue.

Interestingly, before swapping the cabling, `aaru device list` *did* report the non-working configuration as `Supported?=True`. Just an FYI if it's helpful for catching similar errors in the future.

No need to worry about support under Windows (certainly not for my sake). This machine is a relic and the workaround is simple. I really appreciate the quick help, though! I'll go ahead and close the issue.
