### ISSUE TITLE
Device Report: ATAPI_eHAU424   A_7L1P

### ISSUE THREAD

**Issue by gothickitty93** [claunia/DiscImageChef#816]
### Version

5.3.0

### Tested debug version?

- [X] Yes

### Which operating systems have you used?

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Other

### What is the architectural bit size you're using?

- [ ] 32-bit
- [X] 64-bit
- [ ] Unsure or unknown

### What processor are you using?

- [X] An Intel or AMD
- [ ] An ARM or Apple Silicon
- [ ] Unsure or unknown

### Description

Device report: 
[ATAPI_eHAU424   A_7L1P.json.txt](https://github.com/aaru-dps/Aaru/files/12374636/ATAPI_eHAU424.A_7L1P.json.txt)

Did not have all test media available.

### Exact command line used

aaru device report E:

### Expected behavior

A device report.

### Actual behavior

A device report. Yay!

### Output of command execution with debug output enabled

```shell
Json included in previous passage.
```

**Comment by claunia** [comment]
Please do not do device reports using an USB to ATA adapter, they're pretty much useless due to the adapter interferences.

Connect to a real (motherboard integrated or expansion card) ATA controller.
