### ISSUE TITLE
No FAT filesystem found on .ST image by Aaru

### ISSUE THREAD

**Issue by robin-francois** [claunia/DiscImageChef#830]
### Version

5.3.0

### Tested debug version?

- [X] Yes

### Which operating systems have you used?

- [ ] Windows
- [X] Linux
- [ ] macOS
- [ ] Other

### What is the architectural bit size you're using?

- [ ] 32-bit
- [X] 64-bit
- [ ] Unsure or unknown

### What processor are you using?

- [X] An Intel or AMD
- [ ] An ARM or Apple Silicon
- [ ] Unsure or unknown

### Image format

Raw .ST file format

### Application that created the image

Unknown

### What were you doing when it failed?

- [ ] I was converting the image to another format...
- [ ] I was retrieving image information...
- [ ] I was retrieving filesystem information...
- [X] I was listing the filesystem contents...
- [X] I was extracting the filesystem contents...
- [ ] I was creating a metadata sidecar...
- [ ] I was checksumming the image...
- [ ] I was verifying the image...
- [ ] I was calculating the image entropy...

### Filesystem

FAT

### Description

Two .ST images from the same Atari ST game have been downloaded from the Internet. I do not have any information on how the image was created.

One of the image (floppy A) is correctly handled by Aaru. Aaru detects the FAT filesystem and is able to perform file extract.

Aaru does not detect any filesystem from the second image (floppy B). The same image however can be mounted on Linux  (losetup and then standard mount). Files can be accessed and copies from the mounted partition.

.ST images have been shared privately with @claunia 

I cannot exclude that the "faulty" image can be ill-structured.

### Exact command line used

aaru fs info

### Expected behavior

Aaru identifies the filesystem and can extract the files.

### Actual behavior

Aaru does not detect any filesystem

### Output of command execution with debug output enabled

```shell
<Will be inserted later>
```

### Affected image

.ST images have been shared privately with @claunia

**Comment by claunia** [comment]
File is truncated. If you resize it to the correct size it shall work.

![image](https://github.com/aaru-dps/Aaru/assets/1234569/2b660081-5d3c-4de0-ab73-01c5b14cb323)
